-- Drop existing table and policies if they exist
DROP POLICY IF EXISTS "Allow public to insert resources" ON public.resources;
DROP POLICY IF EXISTS "Allow public to view resources" ON public.resources;
DROP TABLE IF EXISTS public.resources CASCADE;

-- Create resources table with complete schema
CREATE TABLE public.resources (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  
  -- Basic Info
  title TEXT NOT NULL,
  subject TEXT NOT NULL,
  semester INTEGER DEFAULT 1,
  department TEXT DEFAULT 'General',
  type TEXT DEFAULT 'Notes' CHECK (type IN ('Notes', 'Solutions', 'Question Papers', 'Lab Reports', 'Other')),
  
  -- File Details
  file_url TEXT NOT NULL,
  file_type TEXT DEFAULT 'pdf',
  file_size BIGINT DEFAULT 0,
  
  -- Uploader Info
  uploader_id TEXT NOT NULL,
  uploader_name TEXT NOT NULL,
  uploader_college TEXT NOT NULL,
  
  -- Privacy & Access Control
  privacy TEXT DEFAULT 'public' CHECK (privacy IN ('public', 'private')),
  restricted_to_university TEXT,
  shared_with TEXT[] DEFAULT ARRAY[]::TEXT[],
  
  -- Additional Info
  batch TEXT DEFAULT '2024',
  tags TEXT[] DEFAULT ARRAY[]::TEXT[],
  
  -- Engagement Metrics
  downloads INTEGER DEFAULT 0,
  average_rating DECIMAL(3,2) DEFAULT 0.0,
  total_ratings INTEGER DEFAULT 0,
  
  -- Timestamps
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- Create indexes for better query performance
CREATE INDEX idx_resources_subject ON public.resources(subject);
CREATE INDEX idx_resources_semester ON public.resources(semester);
CREATE INDEX idx_resources_department ON public.resources(department);
CREATE INDEX idx_resources_privacy ON public.resources(privacy);
CREATE INDEX idx_resources_uploader_id ON public.resources(uploader_id);
CREATE INDEX idx_resources_created_at ON public.resources(created_at DESC);

-- Enable RLS (Row Level Security)
ALTER TABLE public.resources ENABLE ROW LEVEL SECURITY;

-- Policy: Allow anyone to insert (for now)
CREATE POLICY "Allow public to insert resources" 
ON public.resources 
FOR INSERT 
WITH CHECK (true);

-- Policy: Allow anyone to view public resources
CREATE POLICY "Allow public to view public resources" 
ON public.resources 
FOR SELECT 
USING (privacy = 'public' OR auth.uid()::text = uploader_id);

-- Policy: Users can update their own resources
CREATE POLICY "Allow users to update own resources" 
ON public.resources 
FOR UPDATE 
USING (auth.uid()::text = uploader_id) 
WITH CHECK (auth.uid()::text = uploader_id);

-- Policy: Users can delete their own resources
CREATE POLICY "Allow users to delete own resources" 
ON public.resources 
FOR DELETE 
USING (auth.uid()::text = uploader_id);

-- Create reviews table
CREATE TABLE public.reviews (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  resource_id BIGINT NOT NULL REFERENCES public.resources(id) ON DELETE CASCADE,
  user_id TEXT NOT NULL,
  user_name TEXT NOT NULL,
  rating INTEGER NOT NULL CHECK (rating >= 1 AND rating <= 5),
  comment TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
  UNIQUE(resource_id, user_id)
);

-- Create index for reviews
CREATE INDEX idx_reviews_resource_id ON public.reviews(resource_id);
CREATE INDEX idx_reviews_user_id ON public.reviews(user_id);

-- Enable RLS on reviews
ALTER TABLE public.reviews ENABLE ROW LEVEL SECURITY;

-- Reviews policies
CREATE POLICY "Allow public to view reviews" 
ON public.reviews 
FOR SELECT 
USING (true);

CREATE POLICY "Allow anyone to insert reviews" 
ON public.reviews 
FOR INSERT 
WITH CHECK (true);

CREATE POLICY "Allow users to delete own reviews" 
ON public.reviews 
FOR DELETE 
USING (true);
-- Create resource_requests table
CREATE TABLE public.resource_requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  
  -- Request Details
  title TEXT NOT NULL,
  subject TEXT NOT NULL,
  semester INTEGER DEFAULT 1,
  description TEXT,
  
  -- Requester Info
  requested_by_id TEXT NOT NULL,
  requested_by_name TEXT NOT NULL,
  requested_by_college TEXT NOT NULL,
  
  -- Status & Engagement
  status TEXT DEFAULT 'open' CHECK (status IN ('open', 'fulfilled')),
  request_count INTEGER DEFAULT 1,
  
  -- Timestamps
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- Create indexes for requests
CREATE INDEX idx_requests_status ON public.resource_requests(status);
CREATE INDEX idx_requests_created_at ON public.resource_requests(created_at DESC);

-- Enable RLS on resource_requests
ALTER TABLE public.resource_requests ENABLE ROW LEVEL SECURITY;

-- Requests policies
CREATE POLICY "Allow public to view requests" 
ON public.resource_requests 
FOR SELECT 
USING (true);

CREATE POLICY "Allow anyone to insert requests" 
ON public.resource_requests 
FOR INSERT 
WITH CHECK (true);

CREATE POLICY "Allow users to update request count" 
ON public.resource_requests 
FOR UPDATE 
USING (true)
WITH CHECK (true);